function [fitresult, gof] = final_slope_fit(fit_distance, fit_slope, fit_std)
%CREATEFIT(FIT_DISTANCE,FIT_SLOPE,FIT_STD)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : fit_distance
%      Y Output: fit_slope
%      Weights : fit_std
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Feb-2020 02:32:32


%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( fit_distance, fit_slope, fit_std );

% Set up fittype and options.
ft = fittype( 'a*x + b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.54972360829114 0.91719366382981];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );



